## Deliverable 2. Create a Customer Travel Destinations Map.

In [15]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [16]:
# 1. Import the WeatherPy_database.csv file. 

city_data_df = pd.read_csv(r"C:\Users\A Girl's Lenovo\OneDrive\Documents\UW Data Analytics Materials\Module 6\WeatherPY\Weather_Database\WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Eenhana,NaN,-17.4667,16.3333,71.60,83,99,4.61,overcast clouds
1,1,Santa Maria,BR,-29.6842,-53.8069,69.80,100,40,3.44,scattered clouds
2,2,Moerai,PF,-22.4333,-151.3333,80.46,71,100,18.07,light rain
3,3,Cape Town,ZA,-33.9258,18.4232,72.00,88,0,9.22,clear sky
4,4,Tasiilaq,GL,65.6145,-37.6368,30.20,74,75,36.82,light snow

In [17]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 

min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [19]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.

preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]


preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
2,2,Moerai,PF,-22.4333,-151.3333,80.46,71,100,18.07,light rain
5,5,Rikitea,PF,-23.1203,-134.9692,80.64,70,9,9.57,clear sky
15,15,Arraial Do Cabo,BR,-22.9661,-42.0278,76.32,89,100,15.66,overcast clouds
16,16,Jacareacanga,BR,-6.2222,-57.7528,76.96,85,99,0.25,overcast clouds
20,20,Uarini,BR,-2.9900,-65.1083,75.90,93,100,2.24,overcast clouds
23,23,Hithadhoo,MV,-0.6000,73.0833,82.24,73,95,11.59,overcast clouds
29,29,Limbang,MY,4.7500,115.0000,78.80,89,75,9.22,light rain
32,32,Pisco,PE,-13.7000,-76.2167,75.20,69,0,16.11,clear sky
38,38,Butaritari,KI,3.0707,172.7902,81.21,83,0,12.01,clear sky
40,40,Manicore,BR,-5.8092,-61.3003,75.11,95,18,1.45,few clouds

In [20]:
# 4a. Determine if there are any empty rows.

preferred_cities_df.count()

City_ID                175
City                   175
Country                175
Lat                    175
Lng                    175
Max Temp               175
Humidity               175
Cloudiness             175
Wind Speed             175
Current Description    175
dtype: int64

In [22]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.

clean_df = preferred_cities_df.dropna()

clean_df.count()

City_ID                175
City                   175
Country                175
Lat                    175
Lng                    175
Max Temp               175
Humidity               175
Cloudiness             175
Wind Speed             175
Current Description    175
dtype: int64

In [23]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Moerai,PF,80.46,light rain,-22.4333,-151.3333,
5,Rikitea,PF,80.64,clear sky,-23.1203,-134.9692,
15,Arraial Do Cabo,BR,76.32,overcast clouds,-22.9661,-42.0278,
16,Jacareacanga,BR,76.96,overcast clouds,-6.2222,-57.7528,
20,Uarini,BR,75.90,overcast clouds,-2.9900,-65.1083,
23,Hithadhoo,MV,82.24,overcast clouds,-0.6000,73.0833,
29,Limbang,MY,78.80,light rain,4.7500,115.0000,
32,Pisco,PE,75.20,clear sky,-13.7000,-76.2167,
38,Butaritari,KI,81.21,clear sky,3.0707,172.7902,
40,Manicore,BR,75.11,few clouds,-5.8092,-61.3003,

In [24]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.

for index, row in hotel_df.iterrows():

    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"    

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()   
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [35]:
# Adding Dependency
import numpy as np

In [43]:
# 7. Drop the rows where there is no Hotel Name.

# Replace empty string values with NaN panda objects in the Hotel Name column.
hotel_df['Hotel Name'].replace('',np.nan,inplace=True)

# Drop the rows where there are NaN values in the Hotel Name column.
hotel_df.dropna(subset=['Hotel Name'], inplace=True)

# Create new dataframe to store location, weather data and nearest hotel.
clean_hotel_df = hotel_df

clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Moerai,PF,80.46,light rain,-22.4333,-151.3333,Le Manotel
5,Rikitea,PF,80.64,clear sky,-23.1203,-134.9692,Pension Maro'i
15,Arraial Do Cabo,BR,76.32,overcast clouds,-22.9661,-42.0278,Pousada Porto Praia
16,Jacareacanga,BR,76.96,overcast clouds,-6.2222,-57.7528,Casa do Ian😎
23,Hithadhoo,MV,82.24,overcast clouds,-0.6000,73.0833,Scoop Guest House
29,Limbang,MY,78.80,light rain,4.7500,115.0000,Purnama Hotel
32,Pisco,PE,75.20,clear sky,-13.7000,-76.2167,Hotel San Isidro Oficial
38,Butaritari,KI,81.21,clear sky,3.0707,172.7902,Isles Sunset Lodge
40,Manicore,BR,75.11,few clouds,-5.8092,-61.3003,Hotel Durval
44,Atuona,PF,79.11,clear sky,-9.8000,-139.0333,Villa Enata

In [44]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [47]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>

"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [48]:
# 11a. Add a marker layer for each city to the map. 

max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))